# Generated by Django 4.0.5 on 2022-06-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_alter_teacher_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Subjects_taught',
            field=models.CharField(choices=[('1', 'Malayalam'), ('2', 'English'), ('3', 'Computer Science'), ('4', 'History'), ('5', 'Mathematics'), ('6', 'Arabic'), ('7', 'Physics'), ('8', 'Biology'), ('9', 'Chemistry'), ('10', 'Geography')], max_length=5),
        ),
    ]
