# Generated by Django 4.0.5 on 2022-06-16 10:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_alter_teacher_subjects_taught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Subjects_taught',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Malayalam'), ('2', 'English'), ('3', 'Computer Science'), ('4', 'History'), ('5', 'Mathematics'), ('6', 'Arabic'), ('7', 'Physics'), ('8', 'Biology'), ('9', 'Chemistry'), ('10', 'Geography')], max_length=5),
        ),
    ]
