# Generated by Django 4.0.5 on 2022-06-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0008_alter_teacher_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Profile_Picture',
            field=models.ImageField(blank=b'I01\n', upload_to='upload/'),
        ),
    ]
